### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by irandamay** [etienne-martin/mapify#1]
When using this in a Drupal environment, "$" is not available to the functions outside of the (function ($) {...}(jQuery)); block.  Specifically the undefined error is coming from line 442 in jQuery.fn.scrollParent, var parent = $( this );

Not sure if it's the best way, but locally I fixed it for my purposes by moving the closing "}(jQuery));" to the end of the file so the entire plugin was enclosed.

**Comment by etienne-martin** [comment]
The problem should now be fixed, let me know if anything.
