### ISSUE TITLE
Is there any way to group area elements to highlight?

### ISSUE THREAD

**Issue by ekonoval** [etienne-martin/mapify#10]
Hi, I'm excited with  your lib but could you tell me is there any way to group elements to highlight?

![group](https://cloud.githubusercontent.com/assets/3856071/16963499/6699070a-4dff-11e6-8486-c83e9de6d411.png)

For example I'd like to highlight all 3 top items if any of them is hovered. I mean the way they will become blue altogether 

I will be grateful for any reply.

**Comment by etienne-martin** [comment]
It wasn't designed with this in mind.

One thing you can try is to fake the grouping by using only one area for the 3 top items with a 0 pixel wide junction between the elements.

Best of luck to you.

Thanks.

**Comment by ekonoval** [comment]
Thanks for reply,
do you mean replace 3 separate <area/> elements into single one containing all coordinates?

**Comment by etienne-martin** [comment]
Yes by joining the elements together with a 0 pixel-wide junction between the areas.
