### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jameswampler** [etienne-martin/mapify#13]
Any way to have multiple hoverClass: so it is possible to use many styles on the areas? I apologize for posting this here I really have no idea where it goes.

**Comment by dresrios** [comment]
I want to know if it is possible to have different styles of popover, someone could give me help on this.

**Comment by etienne-martin** [comment]
It is now possible. You just need to add a "data-hover-class" attribute on the areas where you want a different hovering style.
