### ISSUE TITLE
Area always on

### ISSUE THREAD

**Issue by iverottesen** [etienne-martin/Mapify#14]
For some use cases it wold be nice if there was an option to always show the area overlay (not only on hover).

**Comment by etienne-martin** [comment]
Thanks for the suggestion.

Here's a workaround until I implement it as a feature: http://jsfiddle.net/2wbp0nyf/8/

**Comment by etienne-martin** [comment]
https://github.com/etienne-martin/Mapify/issues/9

**Comment by shiv001** [comment]
> Thanks for the suggestion.
> 
> Here's a workaround until I implement that feature: http://jsfiddle.net/2wbp0nyf/8/

Yes @etienne-martin It is working. But there is a issue that after highlight, I lost my text on that area. Please check in this jsfiddle also. The text on that part of image is not visible and overlapped by new colour. Is it possible to show text as well? Thank you.
