### ISSUE TITLE
Plugin does not work in internet explorer 

### ISSUE THREAD

**Issue by allsenses** [etienne-martin/mapify#2]
also in example at http://etiennemartin.ca/mapify/

**Comment by allsenses** [comment]
Unable to get property  'add' of undefined or null reference
File: jquery.mapify.min.js, row: 2, column: 1428

**Comment by allsenses** [comment]
It is IE bug. IE still doesn't suport classList on svg element.

**Comment by etienne-martin** [comment]
Sorry for the late response, I've been super busy.
The bug is fixed. It's live on http://etiennemartin.ca/mapify/. I still need to push the fix to GIT. 

Thanks!

**Comment by etienne-martin** [comment]
Pushed.

**Comment by allsenses** [comment]
Great work. Thanks.
