### ISSUE TITLE
Does not seem to click through on mobile

### ISSUE THREAD

**Issue by Cozmoz** [etienne-martin/mapify#25]
Hi,

I am unsure on how to get this to click through on mobile, please assist.

http://www.governmentsolarchecker.com/content/

**Comment by Cozmoz** [comment]
I have put a temporary fix in place:

`    if ("ontouchstart" in window || navigator.msMaxTouchPoints) {
      $( '.mapify-img' ).before( '<a href="http://www.governmentsolarchecker.com/content1/" style="display: block; z-index: 9999; position: absolute; top: 0; left: 0"><img src="http://www.governmentsolarchecker.com/images/regions/spacer.svg" width="555" height="674"></a>' );
    }`

**Comment by etienne-martin** [comment]
Thanks, I'll look at the issue.

**Comment by brockfanning** [comment]
In case this is helpful: I noticed that the isMobile variable seems to be purely for iOS. I just did a quick test on a newer Android phone and an older iPhone, and here are the results:
- iPhone: touch did not seem to do anything
- Android: touch triggers the highlight, but the link itself does not go anywhere

**Comment by etienne-martin** [comment]
I've updated the plugin with a fix for the click on mobile. The bug was introduced in the last pull request.

Let me know if you're still experiencing some problems before I close the issue. 

Thanks.

**Comment by brockfanning** [comment]
@etienne-martin Awesome, that fixed the problem for us, thank you! I'm glad to have been way off in my theorizing. :)
