### ISSUE TITLE
Get multiple area selections

### ISSUE THREAD

**Issue by funktionaer** [etienne-martin/mapify#26]
Hi Etienne, thank you for your work. Works like a charm. Is it possible to have multiple areas highlighted when hovering a special area? Maybe it can be put together with a attribute or id. 
Like
```
<area shape="poly" rel="foo" href="#" coords="...">
<area shape="poly" rel="foo" href="#" coords="...">
<area shape="poly"rel="foo" href="#" coords="...">
```

Cheers,
funktionaer

**Comment by etienne-martin** [comment]
Yes, this is possible with the ```data-group-id``` attribute.

https://github.com/etienne-martin/mapify#highlight-multiple-area

Thanks to @ekonoval  for this feature.
