### ISSUE TITLE
Change class dynamically

### ISSUE THREAD

**Issue by polmp** [etienne-martin/Mapify#27]
Hi,

This plugin is working very well, but I have the following question: Can I change the class and then "reload" the area. For example:

I have the following data-hover-class in one area called "hover-red"
I changed the class to "hover-green" with the following:
```
$("#p3").click(function() {
	$(this).attr("data-hover-class","hover-green");
});
```

But doesn't change the colour of the area in real time.
¿It is possible to do this?

Thanks in advance!

**Comment by etienne-martin** [comment]
I've fixed the issue. The hover class is now assigned dynamically.

**Comment by etienne-martin** [comment]
Oh, I almost forgot. 

If you want the color to change as soon as you click, you must manually trigger a redraw of the area.

Here's an example:
    
```javascript
$("#p3").click(function() {
    $(this).attr("data-hover-class","hover-green");
    // Redraw the area
    $(this).trigger("mouseenter.mapify");
    $(this).trigger("focus.mapify");
    $(this).trigger("touchend.mapify");
});
```

**Comment by polmp** [comment]
Thanks! I'll try it now!

**Comment by polmp** [comment]
Sorry to bother you again, but I found a little bug. At first, it highlights correctly, but when you hover inside the element and resize the page the highlight disappears. 
Also when you resize only the last element triggered appears. You can check it here: http://jsfiddle.net/polmp/2wbp0nyf/7/

Greetings!

**Comment by etienne-martin** [comment]
Fixed: http://jsfiddle.net/2wbp0nyf/8/
