### ISSUE TITLE
keep highlighted on click

### ISSUE THREAD

**Issue by seefelder** [etienne-martin/Mapify#31]
Is there an easy way to implement that the area stays highlighted if clicked (not only mouseover).
If an other area would be clicked then only the new should be highlighted.

is this possible?

**Comment by etienne-martin** [comment]
It's not configurable at the moment.

One way to achieve this effect would be to replace the `mouseenter` with a `click` event and then remove the `mouseout` event in [mapify.js](https://github.com/etienne-martin/Mapify/blob/master/src/mapify.js).

Feel free to implement this as an optional feature. 

Pull requests are welcome 🙂
