### ISSUE TITLE
Can I have 2 highlighted areas on the map?

### ISSUE THREAD

**Issue by wa666ou** [etienne-martin/Mapify#32]
I'd like to have 2 different areas highlighted on the map.

1. Active - has green fill color
2. Booked - has grey fill color

[See the live site](http://kalevipanorama.ee/maja/maja-nr-1/korrus-2/korter-49/) - the active has been used, but it does not work. It seems that I cannot use active and another state on one map.

Click on the button "KORRUSE PLAAN" - it will open the map, where there's a "booked" area (apartment no 4) that is grey.
It should also show apartment no 49 active, but it won't because only one apartment can be highlighted.

Is there a solution?
Thanks!

**Comment by etienne-martin** [comment]
Is this what you're looking for? http://jsfiddle.net/2wbp0nyf/10/

**Comment by etienne-martin** [comment]
No answer, I'm closing the issue. Feel free to reopen it if you want.
