### ISSUE TITLE
Small change related to .pluginInfo in the project's web page

### ISSUE THREAD

**Issue by silviubogan** [etienne-martin/Mapify#34]
In the project's web page, there are two elements with the class `.pluginInfo`, one in the header below the title, and one in the footer of the web page.

They look like this:

![captura de ecran din 2017-10-06 04-19-41](https://user-images.githubusercontent.com/198924/31259229-e4f4cb9c-aa4d-11e7-958b-a1390429144f.png)

```html
<p class="pluginInfo">Tested with Chrome, Firefox, Safari ( Desktop &amp; Mobile ), internet explorer 10 &amp; 11 using jQuery 1.8.1</p>
```
The closing parenthesis remains on the second line with nothing preceding it on that line. I think this is unaesthetic. (Please correct me if I am wrong.)

I suggest that you replace the code above with this:

```html
<p class="pluginInfo">Tested with Chrome, Firefox, Safari (&nbsp;Desktop &amp; Mobile&nbsp;), internet explorer 10 &amp; 11 using jQuery 1.8.1</p>
```

In this way, the two `.pluginInfo` elements will look like this:

![captura de ecran din 2017-10-06 04-24-59](https://user-images.githubusercontent.com/198924/31259305-73183e36-aa4e-11e7-884e-d3e3e80e0372.png)

The screenshots were made using Chrome 61.0.3163.100 (official version on 64-bits) on Ubuntu 17.04 x64 with zoom level set to 100%.

**Comment by etienne-martin** [comment]
You're right @silviubogan, I fixed it. Thanks for your comment.
