### ISSUE TITLE
Support for toggle of always visible layers with certain class

### ISSUE THREAD

**Issue by tlygnersjo** [etienne-martin/Mapify#36]
Hi,

I'm trying to implement Mapify with a svg floor plan that i have and want to depending on value from the database show if its rentable or not. The problem i'm having is that I want depending on if a room is rented out or available set a visible layer (like hover layer). For rented rooms i want it to be red and available rooms should be green. On hover i just want the visible layer to be the same as before and that tooltip is being shown.

Is this some that is possible to do?

Thanks in advance!

**Comment by etienne-martin** [comment]
Take a look at this issue: https://github.com/etienne-martin/Mapify/issues/9
