### ISSUE TITLE
Following links on mobile: single-tap vs double-tap

### ISSUE THREAD

**Issue by brockfanning** [etienne-martin/Mapify#40]
@etienne-martin I need to investigate more, but wanted to get your input as well. As I understand it, on Android and iOS, if the map areas have href attributes, users need to tap twice in order to follow the links: once to focus the area, and then a second time to follow the link. At least that's what it seems like from some quick testing. Do you think it would be appropriate (and if so, possible?) to have an option in this library for eliminating the need for 2 taps? Something like "follow_links_on_first_tap" maybe?

**Comment by etienne-martin** [comment]
@brockfanning, I think that the `instantClickOnMobile ` option is what you're looking for.

https://github.com/etienne-martin/Mapify/blob/c41202987d97adfb55ed97c59460a5c6320de2c7/src/mapify.js#L58

**Comment by etienne-martin** [comment]
It's not mentioned in the doc yet, try it and let me know how it goes.

**Comment by brockfanning** [comment]
@etienne-martin Nice! That works perfectly for iOS. I'm still not seeing it on Android, though. Is that maybe because isMobile is not true for Android?

**Comment by etienne-martin** [comment]
You're right, `isMobile` is only true on iOS:

https://github.com/etienne-martin/Mapify/blob/c41202987d97adfb55ed97c59460a5c6320de2c7/src/mapify.js#L63-L64

Can you create a new issue about that?

Or better, send a PR? :)

**Comment by brockfanning** [comment]
@etienne-martin Sure thing, just submitted #41

**Comment by etienne-martin** [comment]
Thanks @brockfanning
