### ISSUE TITLE
Where do you get the data files?

### ISSUE THREAD

**Issue by rainman20** [etienne-martin/mapify#5]
just a quick question, so where do you get the data from?
for example:

```
<area data-nbmembre="1" alt="Saint-Louis" title="Saint-Louis" href="#" shape="poly" coords="92.394,40.738,
		218.265,178.666,228.589,153.08,225.747,144.878,241.33,128.802,210.934,99.067,211.084,95.177,214.824,86.499,215.273,79.616,
		220.809,70.04,194.924,60.165,196.72,53.881,172.331,48.494,173.229,44.903,150.637,40.738,147.195,52.534,133.878,39.068,
		137.32,28.445,122.657,13.483,92.394,40.738" />
```

is that a GPS coordinate?

**Comment by etienne-martin** [comment]
This is not GPS coordinate, mapify simply makes your [image map](http://www.w3schools.com/tags/att_area_coords.asp) responsive.

You can use tools like this to generate the coords for your map:

https://developer.cdn.mozilla.net/media/uploads/demos/s/u/summerstyle/365ccfd644f2b008c33f0046d2ba1a8f/summer-html-image-ma_1355318513_demo_package/index.html

If your image is a svg you can extract the coords from the file using a simple text editor but you'll still have to edit the data to make it work with your image map.
