### ISSUE TITLE
Mapify content of non-active tabs?

### ISSUE THREAD

**Issue by SamHall** [etienne-martin/mapify#7]
Mapify does exactly what to do.  However, I want to load a 2nd image / map in a tab.
Upon loading, the default active content is mapified.

Switching to the 2nd tab - the image is not mapfied until one manually resizes the browser window.  At that point the first tab's content is not mapified.

Example here:  http://deepzoomchattanooga.com/platbook.php#
(Note:  on the 2nd 'right' tab content, only area 12 is mapped).

Thank you.

**Comment by etienne-martin** [comment]
You can manually trigger the mapify resize event after showing the second image.

`$(window).trigger("resize.mapify");`

Give it a try!

**Comment by SamHall** [comment]
Thank you for the quick reply.
While this works when typed in the browser console, I'm not proficient enough with JQuery to know how to bind this to a click event.

Example:
Page loads - default active 'tab A' and image A is shown - properly mapified.
User clicks tab & image B is shown.
THEN need to apply $(window).trigger("resize.mapify");
If user clicks tab A, and image A is shown, mapify would again need to be called.

Again - I can prove it works in the console, but not sure how to make it happen otherwise.

Thank you.

Sam

**Comment by SamHall** [comment]
I think I have answered my own question regarding how to invoke this.

 

Using:

 

    $(document).ready(function() {  

    $('a[data-toggle="tab"]').click(function() { $(window).trigger("resize.mapify"); });  

    });  

 

This seems to work.


Thanks again,

Sam

**Comment by etienne-martin** [comment]
You got it.
