### ISSUE TITLE
clickable popOver content

### ISSUE THREAD

**Issue by benp** [etienne-martin/mapify#8]
Bonjour Étienne :) I was wondering if there's an easy way to leave the popOver on screen if the mouse hovers on it. I've been able to add URLs with data attributes but the popOver disappears as soon as the mouse leaves the related map area. No sweat if it's too involving (I don't know jQuery enough to tell), as it might be more than what you want the plugin to do. Thanks!

**Comment by etienne-martin** [comment]
You can manually focus a specific area using .focus().

**Comment by benp** [comment]
Thank you! I will investigate :)
