### ISSUE TITLE
Area always highlighted

### ISSUE THREAD

**Issue by mbowzeylo** [etienne-martin/mapify#9]
Hello,

I am wondering how I would make certain area tags always highlighted.

For example...if a suite in an apartment building was sold...I would like to show it as always having a transparent red overlay. Is this possible?

Cheers,
Mike

**Comment by etienne-martin** [comment]
Hi Mike,

Go on http://etiennemartin.ca/mapify/ and paste the following code in the javascript console:

    $("#Map area").eq(3).focus().focus();
    $(".mapify-svg polygon").eq(3).css("fill","#09f");

The 3rd area will be always "highlighted". 

You can add a class to the polygon to control the styling via css.

Thanks,
Etienne.

**Comment by mbowzeylo** [comment]
Hey Etienne,

Thanks for the quick response. Ok, so yeah this works when I put this into the console on my project as well…but how would I implement this into a project code. If I put the same code into a script tag on the bottom of my webpage…it doesn’t work.

Cheers,
Mike

**Comment by etienne-martin** [comment]
Simply add the snippet after declaring the plugin.

Your js should look like this:

    $("img[usemap]").mapify();
    
    // Highlight all areas with the 'highlight' class
    $("area.highlight").each(function(){
	    $(this).focus().focus();
	    $(".mapify-svg polygon").eq($(this).index()).attr("data-highlight", "true");
    });

Control the styling via css:

    .mapify-polygon[data-highlight]{
        fill: #09f;
    }

**Comment by polmp** [comment]
Hi again,

I think this code only works only when we hover on the area before. At first, it doesn't show the area highlighted.
¿Any solution to this?

Thanks again for you nice plugin!

**Comment by etienne-martin** [comment]
![image](https://cloud.githubusercontent.com/assets/9700213/24563681/53388938-161d-11e7-8cde-14fcc1e53c48.png)


Can you send me an example that reproduces the problem?

**Comment by polmp** [comment]
Thanks for your response

This is what is happening to me: http://imgur.com/nmZxyHz

Greetings

**Comment by etienne-martin** [comment]
It looks the line that contains ".focus().focus()" is not targeting the right area.

**Comment by etienne-martin** [comment]
Send me a jsfiddle so I can play around with your code.

**Comment by polmp** [comment]
http://jsfiddle.net/polmp/2wbp0nyf/#&togetherjs=bheskj5tqo
or
http://jsfiddle.net/polmp/2wbp0nyf/

**Comment by etienne-martin** [comment]
Here's the [fixed version](http://jsfiddle.net/2wbp0nyf/6/).

**Comment by polmp** [comment]
This is working perfectly. Thanks again Etienne!

**Comment by polmp** [comment]
Sorry to bother you again, but I found a little bug: When you hover the element and resize the page, the highlight disappears. Also, when you resize a page with two elements highlighted, it only appears the last element you triggered. You can check it here: http://jsfiddle.net/polmp/2wbp0nyf/7/

**Comment by etienne-martin** [comment]
Fixed: http://jsfiddle.net/2wbp0nyf/8/

**Comment by ivanlph** [comment]
Hi etienne,  I am having the same issue that polm, I tried using your fixed version but it doesn't work to me. I am using the popover option. Is there any way to use the always highlighted and the popover together? 

Thanks!

**Comment by thanstein** [comment]
Hey Etienne,
Can you help me to highlight all of the areas when the page load, and change the highlight color on hoover? Im experimenting with your solutions above without luck.

**Comment by gramichal** [comment]
Last fixed version doesn't work on mobile - for example on iPad - there is no highlighted elements until you tap them - then they stay highlighted - but not after (re)load page.

**Comment by lukasz-pawlowicz** [comment]
Hi Everyone,
has someone managed to fix the highlight areas on mobile devices?
My function:
```
function color_allareas() {
    var $highlightCounter = 0;
    $("#image-map area").each(function() {
        $(this).focus().focus();
        $(this).eq($highlightCounter).trigger("mouseenter.mapify").trigger("focus.mapify").trigger("touchend.mapify");
        $(".mapify-svg polygon").eq($highlightCounter).css("fill", $(this).attr("data-color"));
        $highlightCounter++;
    });
    // PREVENT FROM SCROLLING TO MAP 
    window.scrollTo(0, 0);
}
```

**Comment by UmarEhsan** [comment]
Hi Everyone,
Can anyone help me to show the text on the area tag is it possible?

**Comment by Vikiram27** [comment]
Always highlight on load is not working on iPhone... Can you please send script code?
